// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pegiensgnptpdnfopnoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZ2llbnNnbnB0cGRuZm9wbm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzU4ODEsImV4cCI6MjA2NzY1MTg4MX0.GgtyMgB-CC2P51mu0yp1QmtzoJXrU6r7l2YwxEdCfGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: false, // Manual refresh to avoid realtime connections
  },
  db: {
    schema: 'public'
  },
  // 👇 Optionally remove or comment out the entire `realtime` block if not used
  // realtime: {} // Leaving this empty does not initiate any realtime connection
});